//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardiansOfTheGalaxy.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class constraint
    {
        public int id { get; set; }
        public string description { get; set; }
        public int permanent { get; set; }
        public int ranking { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> worker_id { get; set; }
        public int constraint_type_id { get; set; }
    
        public virtual constraint_type constraint_type { get; set; }
        public virtual worker worker { get; set; }
    }
}
