//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardiansOfTheGalaxy.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class excemption
    {
        public excemption()
        {
            this.shift_type_excemptions = new HashSet<shift_type_excemptions>();
            this.worker_excemptions = new HashSet<worker_excemptions>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual ICollection<shift_type_excemptions> shift_type_excemptions { get; set; }
        public virtual ICollection<worker_excemptions> worker_excemptions { get; set; }
    }
}
