//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardiansOfTheGalaxy.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<constraint_type> constraint_type { get; set; }
        public virtual DbSet<constraint> constraints { get; set; }
        public virtual DbSet<excemption> excemptions { get; set; }
        public virtual DbSet<rank> ranks { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<shift> shifts { get; set; }
        public virtual DbSet<shift_type> shift_type { get; set; }
        public virtual DbSet<shift_type_excemptions> shift_type_excemptions { get; set; }
        public virtual DbSet<worker> workers { get; set; }
        public virtual DbSet<worker_excemptions> worker_excemptions { get; set; }
    }
}
