//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardiansOfTheGalaxy.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int shift_type_id { get; set; }
        public int worker_id { get; set; }
        public int confirmed { get; set; }
    
        public virtual shift_type shift_type { get; set; }
        public virtual worker worker { get; set; }
    }
}
