//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardiansOfTheGalaxy.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        public worker()
        {
            this.constraints = new HashSet<constraint>();
            this.shifts = new HashSet<shift>();
            this.worker_excemptions = new HashSet<worker_excemptions>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public int phone { get; set; }
        public int rank_id { get; set; }
        public int role_id { get; set; }
    
        public virtual ICollection<constraint> constraints { get; set; }
        public virtual rank rank { get; set; }
        public virtual role role { get; set; }
        public virtual ICollection<shift> shifts { get; set; }
        public virtual ICollection<worker_excemptions> worker_excemptions { get; set; }
    }
}
